# Generated by Django 6.0.4 on 2026-04-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.CharField(default='', max_length=255)),
                ('song_name', models.CharField(default='', max_length=255)),
                ('composer_name', models.CharField(blank=True, default='', max_length=255)),
                ('lyricist_name', models.CharField(blank=True, default='', max_length=255)),
                ('tuning_name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('artist_name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
