# Generated by Django 6.0.4 on 2026-04-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(default='Unknown', max_length=100)),
                ('link', models.URLField()),
                ('aliases', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('country', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
    ]
